export const SERVICES = {
  AUTH: 'AUTH_SERVICE',
  PRODUCT: 'PRODUCT_SERVICE',
  ORDER: 'ORDER_SERVICE',
  PAYMENT: 'PAYMENT_SERVICE',
  INVENTORY: 'INVENTORY_SERVICE',
  NOTIFICATION: 'NOTIFICATION_SERVICE',
} as const;

export const PORTS = {
  API_GATEWAY: 3000,
  AUTH: 3001,
  PRODUCT: 3002,
  ORDER: 3003,
  PAYMENT: 3004,
  INVENTORY: 3005,
  NOTIFICATION: 3006,
} as const;
